name: CW Contracts Test Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - contracts/**
      - .github/workflows/deploy-cw-contracts.yml
      - scripts/generate_wasm.sh

jobs:
  Build:
    name: Build & Deploy CW Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Archway Blockchain
        run: |
          cp ./scripts/archway/docker-compose.yml .
          docker compose -f docker-compose.yml up -d

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install cw-check
        run: |
          cargo install cosmwasm-check --locked

      - name: Compile WASM
        run: |
          sudo chmod -R 777 artifacts
          sudo chmod -R 777 scripts
          bash ./scripts/generate_wasm.sh

      - name: Deploy WASM
        run: |
          container=$(docker ps --format '{{.Names}}')
          docker exec $container sh -c "rm /contracts/cw_common*.wasm"
          docker exec $container chmod +x /contracts/deploy_cw.sh
          docker exec $container sh /contracts/deploy_cw.sh
